Repository woowacourse-study/2023-BookOverFlow, pull requests merged in 2023-07, with the labels that each got.

#3 [링링] 운영체제와 정보기술의 원리 - 1장, 2장
  운영체제와 정보기술의 원리/1장/링링.md
  운영체제와 정보기술의 원리/2장/링링.md
Labels: 링링 👻

#2 [로피] 운영체제와 정보기술의 원리 - 1장, 2장
  .idea/.gitignore
  운영체제와 정보기술의 원리/1장/.gitkeep
  운영체제와 정보기술의 원리/1장/로피.md
  운영체제와 정보기술의 원리/2장/.gitkeep
  운영체제와 정보기술의 원리/2장/로피.md
Labels: 로피 🥨

#4 [산군] 운영체제와 정보기술의 원리 - 1장, 2장
  운영체제와 정보기술의 원리/1장/산군.md
  운영체제와 정보기술의 원리/2장/산군.md
Labels: 군산 🐯
