Repository woowacourse-study/2023-BookOverFlow, pull requests merged in 2023-08, with the labels that each got.

#6 [반달] 운영체제와 정보기술의 원리 - 3장, 4장, 5장
  운영체제와 정보기술의 원리/3장/반달.md
  운영체제와 정보기술의 원리/4장/반달.md
  운영체제와 정보기술의 원리/5장/반달.md
Labels: 반달 🌓

#8 [링링] 운영체제와 정보기술의 원리 - 3장, 4장, 5장
  운영체제와 정보기술의 원리/3장/링링.md
  운영체제와 정보기술의 원리/4장/링링.md
  운영체제와 정보기술의 원리/5장/링링.md
Labels: 링링 👻

#7 [하티] 운영체제와 정보기술의 원리 - 3장, 4장, 5장
  운영체제와 정보기술의 원리/3장/하티.md
  운영체제와 정보기술의 원리/4장/하티.md
  운영체제와 정보기술의 원리/5장/하티.md
Labels: 하티 🕶️

#11 [하티] 운영체제와 정보기술의 원리 - 6장
  운영체제와 정보기술의 원리/6장/하티.md
Labels: 하티 🕶️

#14 [반달] 운영체제와 정보기술의 원리 - 6장
  운영체제와 정보기술의 원리/6장/반달.md
Labels: 반달 🌓

#9 [로피] 운영체제와 정보기술의 원리 - 3장, 4장, 5장
  운영체제와 정보기술의 원리/3장/로피.md
  운영체제와 정보기술의 원리/4장/로피.md
  운영체제와 정보기술의 원리/5장/로피.md
Labels: 로피 🥨
